#!/usr/bin/env bash
#
# failure-sim-demo.sh — demonstrate the resilience bonus (docs/protocol.md §17.3):
# retry/backoff recovery on a transient failure, plus a dead-letter queue entry
# for a doomed (unreachable) call that exhausts all retries.
#
# It (re)starts ONLY the command-agent with FAILURE_SIMULATION=true, lets it run
# the mission, then queries the dashboard:
#   * GET /api/dead-letters  — asserts >= 1 dead letter was recorded
#   * GET /api/audit         — shows the retry/backoff audit rows
# Finally it restores the command-agent to the default (FAILURE_SIMULATION=false)
# code path so the demo is left exactly as it was found.
#
# The whole thing is idempotent: re-running it simply recreates the command-agent
# and reruns the mission. The default `false` path is never changed permanently.
#
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."
REPO_ROOT="$(pwd)"

# Pick up host-port overrides from the repo .env (if present).
ENV_FILE="${REPO_ROOT}/.env"
# shellcheck disable=SC1090
[[ -f "${ENV_FILE}" ]] && { set -a; . "${ENV_FILE}"; set +a; }

COMPOSE="docker compose"
HOST="${A2A_HOST:-localhost}"
DASHBOARD="http://${HOST}:${DASHBOARD_HOST_PORT:-8080}"

# A throwaway compose override that flips FAILURE_SIMULATION on for the command
# agent only. We never edit docker-compose.yml; we layer this override with -f.
# (The command agent's base value is "false"; this override wins for this run.)
OVERRIDE_FILE="$(mktemp -t failure-sim-override.XXXXXX.yml)"
cleanup() { rm -f "${OVERRIDE_FILE}"; }
trap cleanup EXIT

cat >"${OVERRIDE_FILE}" <<'YAML'
# Generated by scripts/failure-sim-demo.sh — flips FAILURE_SIMULATION on for the
# command agent so the retry/backoff + dead-letter resilience path runs.
services:
  command-agent:
    environment:
      FAILURE_SIMULATION: "true"
YAML

echo "============================================================================"
echo " Operation Echo Shield — resilience demo (retry/backoff + dead-letter queue)"
echo "============================================================================"
echo ""
echo "What this does (docs/protocol.md §17.3):"
echo "  1. Recreates the command-agent with FAILURE_SIMULATION=true."
echo "  2. Before the real mission, the command agent:"
echo "       - fires one TRANSIENT failure that recovers on retry attempt 2"
echo "         (recorded in audit_logs), and"
echo "       - fires one DOOMED call to an unreachable URL that exhausts all"
echo "         retries and lands in the dead_letters table (status=dead-letter)."
echo "  3. The mission then proceeds normally and completes."
echo "  4. We assert >=1 dead letter via the dashboard and show the audit rows."
echo "  5. We restore the command-agent to the default FAILURE_SIMULATION=false."
echo ""

# Capture the CURRENT mission started_at first: the stale run is already
# "completed", so we must wait for a *fresh* run (a new started_at), not just any
# "completed" status, before checking the dead-letter queue.
mission_started_at() {
	curl -sS --max-time 5 "${DASHBOARD}/api/mission" 2>/dev/null | python3 -c '
import json,sys
try:
    m=json.load(sys.stdin); m=m.get("mission",m) if isinstance(m,dict) else m
    print((m or {}).get("started_at","") or "")
except Exception:
    print("")
' 2>/dev/null || true
}
BASELINE_STARTED="$(mission_started_at)"
export BASELINE_STARTED

echo "==> Recreating command-agent with FAILURE_SIMULATION=true ..."
${COMPOSE} -f docker-compose.yml -f "${OVERRIDE_FILE}" up -d --no-deps --force-recreate command-agent

# Wait for the command agent to autostart and complete a FRESH mission (a new
# started_at distinct from the baseline) — it runs after MISSION_START_DELAY_SECONDS.
echo "==> Waiting for a fresh mission run to complete (up to ~140s) ..."
MISSION_OK=0
for _ in $(seq 1 70); do
	BODY="$(curl -sS --max-time 5 "${DASHBOARD}/api/mission" 2>/dev/null || true)"
	if [[ -n "${BODY}" ]] && echo "${BODY}" | python3 -c '
import json,sys,os
m=json.load(sys.stdin); m=m.get("mission",m) if isinstance(m,dict) else m
status=str((m or {}).get("status","")).lower()
started=(m or {}).get("started_at","") or ""
assert status=="completed" and started and started!=os.environ.get("BASELINE_STARTED",""), \
    "not a fresh completion yet (status=%r started=%r)"%(status,started)
' >/dev/null 2>&1; then
		MISSION_OK=1
		break
	fi
	sleep 2
done

if [[ "${MISSION_OK}" -eq 1 ]]; then
	echo "    Fresh mission completed."
else
	echo "    (Fresh mission did not report completed in time; checking dead letters anyway.)"
fi
echo ""

# --------------------------------------------------------------------------
# Assert >= 1 dead letter.
# --------------------------------------------------------------------------
echo "==> GET ${DASHBOARD}/api/dead-letters"
DLQ_OK=0
DLQ_BODY=""
for _ in $(seq 1 10); do
	DLQ_BODY="$(curl -sS --max-time 10 "${DASHBOARD}/api/dead-letters" 2>/dev/null || true)"
	if [[ -n "${DLQ_BODY}" ]] && echo "${DLQ_BODY}" | python3 -c '
import json,sys
r=json.load(sys.stdin); rows=r
if isinstance(r,dict):
    for k in ("dead_letters","deadLetters","results","rows"):
        if k in r: rows=r[k]; break
sys.exit(0 if isinstance(rows,list) and len(rows)>=1 else 1)
' >/dev/null 2>&1; then
		break
	fi
	sleep 2
done
if [[ -n "${DLQ_BODY}" ]]; then
	if echo "${DLQ_BODY}" | python3 -c '
import json,sys
r=json.load(sys.stdin)
rows=r
if isinstance(r, dict):
    for k in ("dead_letters","deadLetters","results","rows"):
        if k in r:
            rows=r[k]; break
assert isinstance(rows, list), "not a list: %r"%type(rows)
assert len(rows) >= 1, "expected >=1 dead letter, got %d"%len(rows)
print("    %d dead letter(s) recorded:" % len(rows))
for d in rows:
    rcpt=d.get("recipient") or d.get("recipient_url") or "?"
    err=d.get("last_error") or d.get("lastError") or ""
    att=d.get("attempts")
    print("      - recipient=%s attempts=%s last_error=%s" % (rcpt, att, str(err)[:80]))
' 2>/dev/null; then
		DLQ_OK=1
	fi
fi

if [[ "${DLQ_OK}" -eq 1 ]]; then
	echo "  [PASS] dead-letter queue has >= 1 entry"
else
	echo "  [FAIL] expected >= 1 dead letter from /api/dead-letters"
	echo "         -> ${DLQ_BODY:0:300}"
fi
echo ""

# --------------------------------------------------------------------------
# Show the retry/backoff audit rows.
# --------------------------------------------------------------------------
echo "==> Retry / backoff audit rows (GET ${DASHBOARD}/api/audit):"
AUDIT_BODY="$(curl -sS --max-time 10 "${DASHBOARD}/api/audit" 2>/dev/null || true)"
if [[ -n "${AUDIT_BODY}" ]]; then
	echo "${AUDIT_BODY}" | python3 -c '
import json,sys
r=json.load(sys.stdin)
rows=r
if isinstance(r, dict):
    for k in ("auditLogs","audit_logs","audit","rows","results"):
        if k in r:
            rows=r[k]; break
if not isinstance(rows, list):
    sys.exit(0)
shown=0
for a in rows:
    blob=json.dumps(a).lower()
    if "retry" in blob or "backoff" in blob or "attempt" in blob or "dead" in blob:
        action=a.get("action","")
        actor=a.get("actor","")
        details=a.get("details_json") or a.get("details") or ""
        print("      - %-20s %-22s %s" % (actor, action, str(details)[:90]))
        shown+=1
if shown==0:
    print("      (no retry/backoff audit rows matched; see full /api/audit)")
' 2>/dev/null || echo "      (could not parse audit response)"
else
	echo "      (no audit response)"
fi
echo ""

# --------------------------------------------------------------------------
# Restore the default (FAILURE_SIMULATION=false) code path.
# --------------------------------------------------------------------------
echo "==> Restoring command-agent to the default FAILURE_SIMULATION=false path ..."
${COMPOSE} up -d --no-deps --force-recreate command-agent

echo ""
echo "==> Done. The galaxy is back on the nominal (clean) path."
echo "    Dead-Letter Queue panel: ${DASHBOARD}  (resets to 'nominal' on the next clean run)."

if [[ "${DLQ_OK}" -eq 1 ]]; then
	echo "    Result: PASS"
else
	echo "    Result: FAIL" >&2
	exit 1
fi
